<a href="https://colab.research.google.com/github/skillzTheProgrammer/API-Examples-Web/blob/main/mixing_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import Tensorflow
import tensorflow as tf
tf.__version__

'2.11.0'

In [20]:
#create tensors with tf constant()
scalar = tf.constant([6,9,4,3,5])
scalar

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([6, 9, 4, 3, 5], dtype=int32)>

In [21]:
scalar.ndim


1

In [7]:
data = [
    [1,2],
    [3,4],
    [5,6]
]
vector = tf.constant(data)
vector

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [8]:
vector.ndim

2

In [14]:
matrix_data = [
    [
        [1,2,3,4],
        # [4,43,2],
      [4,56,3,6]
    ]
]
matrix = tf.constant(matrix_data)
matrix

<tf.Tensor: shape=(1, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 4, 56,  3,  6]]], dtype=int32)>

In [15]:
matrix.ndim

3